# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: Kueens-b
      MONGO_INITDB_ROOT_PASSWORD: Kueens111
      